### ISSUE TITLE
remove system.out

### ISSUE THREAD

**Issue by FlorianZipser** [korpling/pepperModules-ANNISModules#1]
There seems to be an unnecessary output:

sortTimelineRelationsByStart: Both the timeline for Token salt:/kidko/Mo01MD_09/Mo01MD_09_graph#sTok9209 and salt:/kidko/Mo01MD_09/Mo01MD_09_graph#sTok7674 is 1533
sortTimelineRelationsByStart: Both the timeline for Token salt:/kidko/Mo01MD_09/Mo01MD_09_graph#sTok9210 and salt:/kidko/Mo01MD_09/Mo01MD_09_graph#sTok7675 is 1534

since this is not interpretable for the user it might be removed.

**Comment by thomaskrause** [comment]
Was removed when refactoring the virtual token generation (1a794205b66b78184e420d9e6b21895b0e3524e5)
