### ISSUE TITLE
Allow "+" to be used in identifiers

### ISSUE THREAD

**Issue by sdruskat** [korpling/pepperModules-ANNISModules#13]
What is the used ANNIS version?
**3.5.0-preview1 (rev. 4ac25044a5, built 2016-10-18 12:19:11)**

What browser and operating system did you use?
**Firefox 50.0.2 on Ubuntu 16.04.1**

What steps will reproduce the problem?
1. **Create an annotation with qualified name `namespace::name+:value`** 
2. **Export to ANNIS format with [ANNISExporter](https://github.com/korpling/pepperModules-ANNISModules/#details)**
3. **ANNISExporter will attempt to replace *invalid identifier* with another value: "replaced invalid ANNIS identifier name+ with name%2B"**
4. **Annotation is not displayed in ANNIS**

What is the expected result?
**ANNIS accepts annotations with name `{name}+`. If necessary, queries should encode `+`.**

What happens instead?
**ANNISExporter replaces `+` with `%2B`**

Please provide any additional information below. Also please add a screenshot if possible.
**According to [W3C](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1), the `+` char is only used in *application/x-www-form-urlencoded*s replacing spaces.**

**See also: [RFC1738](https://tools.ietf.org/html/rfc1738), [SO answer](http://stackoverflow.com/a/1006074/731040), [SO comment](http://stackoverflow.com/questions/1005676/urls-and-plus-signs#comment14903296_1006074).**

**Comment by thomaskrause** [comment]
We are using the annotation name in AQL and must be more restrictive than URL encoding. E.g. we might not be able to use `+` in future operator names when we allow this to be valid annotation names. In some sense, the annotation name is more similar to a variable name in programming languages than an URL identifier (at least for AQL, for Salt IDs this is a different thing).

Falling back to `%2B` is a convenience alternative to completely failing the export or removing the annotation. That it uses URL-like encoding does not mean that all valid URL strings are valid AQL annotation names.

**Comment by amir-zeldes** [comment]
@thomaskrause what about `.`? We recently ran into some import data from XML with keys containing periods, since it's actually allowed in XML attributes, but AQL seems to forbid it, e.g. 

sentence.mood="imperative"
