### ISSUE TITLE
Adding document-level metadata

### ISSUE THREAD

**Issue by dlukes** [korpling/pepperModules-ANNISModules#14]
Is there any standardized way to inject metadata about the corpus documents at the export stage, or should I just create a `corpus_annotation.tab` manually? If there is some kind of "best practice" concerning this discussed somewhere in the ANNIS or Pepper documentation, please point me to it -- apologies, but I wasn't able to find it myself :(

**Comment by amir-zeldes** [comment]
Yes, this is possible, though you would do it already at the import stage, not during export. See the property `pepper.before.readMeta` described here:

http://corpus-tools.org/pepper/generalCustomizationProperties.html
