### ISSUE TITLE
enhancement for resolver

### ISSUE THREAD

**Issue by FlorianZipser** [korpling/pepperModules-ANNISModules#2]
In case that dominance edges have no subtype, an additional entry in the mappings cell in resolver_vis_map.annis is necessary:

edge_type:null

**Comment by FlorianZipser** [comment]
@amir-zeldes

**Comment by amir-zeldes** [comment]
Can all visualizers understand this or is this something special in case the visualizer is set to "tree"?

**Comment by thomaskrause** [comment]
Tree is currently the only visualizer which implements the "edge_type" mapping

**Comment by thomaskrause** [comment]
Fixed in 9fdbc1eced4d54d7356a099b17716a6414c8fe979fdbc1eced4d54d7356a099b17716a6414c8fe97
